param([string]$WorkbookPath = "outputs\quarter_planning_step2.xlsm")

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$sourceWorkbook = if ([System.IO.Path]::IsPathRooted($WorkbookPath)) { $WorkbookPath } else { Join-Path $repoRoot $WorkbookPath }
if (!(Test-Path -LiteralPath $sourceWorkbook)) { throw "Workbook not found: $sourceWorkbook" }

$nodeExecutable = $env:QUARTER_PLANNING_NODE_EXECUTABLE
if ([string]::IsNullOrWhiteSpace($nodeExecutable)) { $nodeExecutable = "node" }

$temporaryDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("restricted-ts-vba-poc-excel-" + [Guid]::NewGuid().ToString("N"))
$temporaryWorkbook = Join-Path $temporaryDirectory "restricted-ts-vba-poc.xlsm"
$generatedDirectory = Join-Path $temporaryDirectory "generated"
$sourcePath = Join-Path $repoRoot "poc\restricted-ts-vba\src\planning-engine.ts"
$generatedVbaPath = Join-Path $generatedDirectory "QpRestrictedPlanningEngine.bas"

$excel = $null
$workbook = $null
$vbProject = $null
$vbComponents = $null
$engineComponent = $null
$engineCodeModule = $null
$harnessComponent = $null
$harnessCodeModule = $null
$existingExcelProcessIds = @(Get-Process EXCEL -ErrorAction SilentlyContinue | ForEach-Object { $_.Id })

try {
    New-Item -ItemType Directory -Path $temporaryDirectory | Out-Null
    Copy-Item -LiteralPath $sourceWorkbook -Destination $temporaryWorkbook

    & $nodeExecutable ".\scripts\emit_restricted_ts_vba_poc.mjs" $sourcePath $generatedDirectory "QpRestrictedPlanningEngine"
    if ($LASTEXITCODE -ne 0) { throw "restricted TypeScript-to-VBA emission failed" }
    if (!(Test-Path -LiteralPath $generatedVbaPath)) { throw "Generated VBA module not found: $generatedVbaPath" }

    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $excel.EnableEvents = $false
    $excel.AutomationSecurity = 1
    $workbook = $excel.Workbooks.Open($temporaryWorkbook, 0, $false)
    $vbProject = $workbook.VBProject
    $vbComponents = $vbProject.VBComponents

    $engineComponent = $vbComponents.Add(1)
    $engineComponent.Name = "QpRestrictedPlanningEngine"
    $engineCodeModule = $engineComponent.CodeModule
    $engineCodeModule.AddFromString((Get-Content -LiteralPath $generatedVbaPath -Raw -Encoding ASCII))

    $harnessSource = @'
Option Explicit

Public Function RunRestrictedEmitterScalarProbe() As Double
    RunRestrictedEmitterScalarProbe = QPT_plannedDuration(10, 0.8) * 100 + QPT_allocateDays(3)
End Function

Public Function RunRestrictedEmitterArrayProbe() As Double
    Dim estimates As Variant
    Dim results As Variant
    estimates = Array(4, 0, 5)
    results = Array(0, 0, 0)
    QPT_scheduleDurations estimates, 0.8, results
    RunRestrictedEmitterArrayProbe = CDbl(results(0)) * 100 + CDbl(results(1)) * 10 + CDbl(results(2))
End Function

Public Function RunRestrictedEmitterZeroBaseProbe() As Long
    Dim values As Variant
    ReDim values(1 To 2)
    On Error GoTo ExpectedError
    QPT_smoke values
    RunRestrictedEmitterZeroBaseProbe = 0
    Exit Function
ExpectedError:
    If Err.Number = 5 And Err.Source = "QpRestrictedPlanningEngine" Then
        RunRestrictedEmitterZeroBaseProbe = 1
    Else
        RunRestrictedEmitterZeroBaseProbe = -1
    End If
End Function
'@
    $harnessComponent = $vbComponents.Add(1)
    $harnessComponent.Name = "QpRestrictedEmitterHarness"
    $harnessCodeModule = $harnessComponent.CodeModule
    $harnessCodeModule.AddFromString($harnessSource)

    $scalarResult = [double]$excel.Run("'" + $workbook.Name + "'!RunRestrictedEmitterScalarProbe")
    if ($scalarResult -ne 1303) { throw "return/helper/while probe expected 1303, received $scalarResult" }
    Write-Host "PASS generated return values, helper calls, Math.ceil, and while loop run in Excel"

    $arrayResult = [double]$excel.Run("'" + $workbook.Name + "'!RunRestrictedEmitterArrayProbe")
    if ($arrayResult -ne 507) { throw "ByRef array probe expected 507, received $arrayResult" }
    Write-Host "PASS generated ByRef output array propagates scheduler results (507)"

    $zeroBaseResult = [int]$excel.Run("'" + $workbook.Name + "'!RunRestrictedEmitterZeroBaseProbe")
    if ($zeroBaseResult -ne 1) { throw "zero-based array guard did not raise the expected VBA error: $zeroBaseResult" }
    Write-Host "PASS generated runtime guard rejects non-zero-based arrays"
    Write-Host "GO for a restricted-emitter scheduler spike"
} finally {
    if ($harnessCodeModule -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($harnessCodeModule) | Out-Null; $harnessCodeModule = $null }
    if ($harnessComponent -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($harnessComponent) | Out-Null; $harnessComponent = $null }
    if ($engineCodeModule -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($engineCodeModule) | Out-Null; $engineCodeModule = $null }
    if ($engineComponent -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($engineComponent) | Out-Null; $engineComponent = $null }
    if ($vbComponents -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($vbComponents) | Out-Null; $vbComponents = $null }
    if ($vbProject -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($vbProject) | Out-Null; $vbProject = $null }
    if ($workbook -ne $null) { $workbook.Close($false); [System.Runtime.InteropServices.Marshal]::ReleaseComObject($workbook) | Out-Null; $workbook = $null }
    if ($excel -ne $null) { $excel.Quit(); [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null; $excel = $null }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()

    for ($attempt = 0; $attempt -lt 50; $attempt++) {
        $automationProcesses = @(Get-Process EXCEL -ErrorAction SilentlyContinue | Where-Object { $existingExcelProcessIds -notcontains $_.Id })
        if ($automationProcesses.Count -eq 0) { break }
        Start-Sleep -Milliseconds 100
    }
    $automationProcesses = @(Get-Process EXCEL -ErrorAction SilentlyContinue | Where-Object { $existingExcelProcessIds -notcontains $_.Id })
    foreach ($process in $automationProcesses) {
        if ($process.MainWindowHandle -eq 0) { Stop-Process -Id $process.Id -Force }
    }

    if (Test-Path -LiteralPath $temporaryDirectory) {
        $resolvedTempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath()).TrimEnd('\') + '\'
        $resolvedTarget = [System.IO.Path]::GetFullPath($temporaryDirectory)
        if (!$resolvedTarget.StartsWith($resolvedTempRoot, [System.StringComparison]::OrdinalIgnoreCase) -or !(Split-Path -Leaf $resolvedTarget).StartsWith("restricted-ts-vba-poc-excel-")) {
            throw "Refusing to remove unexpected PoC directory: $resolvedTarget"
        }
        Remove-Item -LiteralPath $resolvedTarget -Recurse -Force
    }
}
