param([string]$WorkbookPath = "outputs\quarter_planning_step2.xlsm")

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$sourceWorkbook = if ([System.IO.Path]::IsPathRooted($WorkbookPath)) { $WorkbookPath } else { Join-Path $repoRoot $WorkbookPath }
if (!(Test-Path -LiteralPath $sourceWorkbook)) { throw "Workbook not found: $sourceWorkbook" }

$nodeExecutable = $env:QUARTER_PLANNING_NODE_EXECUTABLE
if ([string]::IsNullOrWhiteSpace($nodeExecutable)) { $nodeExecutable = "node" }

$temporaryDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("tstvba-poc-excel-" + [Guid]::NewGuid().ToString("N"))
$temporaryWorkbook = Join-Path $temporaryDirectory "typescript-to-vba-poc.xlsm"
$safeOutputDirectory = Join-Path $temporaryDirectory "safe"
$byValOutputDirectory = Join-Path $temporaryDirectory "byval"
$safeSource = Join-Path $repoRoot "poc\typescript-to-vba\src\safe-smoke.ts"
$byValSource = Join-Path $repoRoot "poc\typescript-to-vba\probes\byval-output.ts"
$safeVbaPath = Join-Path $safeOutputDirectory "PlanningPocSafe.bas"
$byValVbaPath = Join-Path $byValOutputDirectory "PlanningPocByVal.bas"

$excel = $null
$workbook = $null
$vbProject = $null
$vbComponents = $null
$safeComponent = $null
$safeCodeModule = $null
$byValComponent = $null
$byValCodeModule = $null
$harnessComponent = $null
$harnessCodeModule = $null
$existingExcelProcessIds = @(Get-Process EXCEL -ErrorAction SilentlyContinue | ForEach-Object { $_.Id })

try {
    New-Item -ItemType Directory -Path $temporaryDirectory | Out-Null
    Copy-Item -LiteralPath $sourceWorkbook -Destination $temporaryWorkbook

    & $nodeExecutable ".\scripts\transpile_typescript_to_vba_poc.mjs" $safeSource $safeOutputDirectory "PlanningPocSafe.bas"
    if ($LASTEXITCODE -ne 0) { throw "safe smoke transpilation failed" }
    & $nodeExecutable ".\scripts\transpile_typescript_to_vba_poc.mjs" $byValSource $byValOutputDirectory "PlanningPocByVal.bas"
    if ($LASTEXITCODE -ne 0) { throw "ByVal probe transpilation failed" }
    if (!(Test-Path -LiteralPath $safeVbaPath)) { throw "Generated safe module not found: $safeVbaPath" }
    if (!(Test-Path -LiteralPath $byValVbaPath)) { throw "Generated ByVal module not found: $byValVbaPath" }

    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $excel.EnableEvents = $false
    $excel.AutomationSecurity = 1
    $workbook = $excel.Workbooks.Open($temporaryWorkbook, 0, $false)
    $vbProject = $workbook.VBProject
    $vbComponents = $vbProject.VBComponents

    $safeComponent = $vbComponents.Add(1)
    $safeComponent.Name = "TstVbaPocSafe"
    $safeCodeModule = $safeComponent.CodeModule
    $safeCodeModule.AddFromString((Get-Content -LiteralPath $safeVbaPath -Raw -Encoding ASCII))

    $byValComponent = $vbComponents.Add(1)
    $byValComponent.Name = "TstVbaPocByVal"
    $byValCodeModule = $byValComponent.CodeModule
    $byValCodeModule.AddFromString((Get-Content -LiteralPath $byValVbaPath -Raw -Encoding ASCII))

    $harnessSource = @'
Option Explicit

Public Function RunTstVbaSafeSmoke() As Long
    Dim valueItems As Variant
    valueItems = Array(1, 2)
    QP_safe_smoke_summarize valueItems
    RunTstVbaSafeSmoke = 1
End Function

Public Function RunTstVbaByValProbe() As Double
    Dim valueItems As Variant
    Dim resultItems As Variant
    valueItems = Array(1, 2)
    resultItems = Array(0, 0)
    QP_byval_output_mutateResults valueItems, resultItems
    RunTstVbaByValProbe = CDbl(resultItems(0)) * 10 + CDbl(resultItems(1))
End Function
'@
    $harnessComponent = $vbComponents.Add(1)
    $harnessComponent.Name = "TstVbaPocHarness"
    $harnessCodeModule = $harnessComponent.CodeModule
    $harnessCodeModule.AddFromString($harnessSource)

    $safeResult = [int]$excel.Run("'" + $workbook.Name + "'!RunTstVbaSafeSmoke")
    if ($safeResult -ne 1) { throw "Safe smoke did not run: $safeResult" }
    Write-Host "PASS generated safe smoke compiles and runs in Excel"

    $byValResult = [double]$excel.Run("'" + $workbook.Name + "'!RunTstVbaByValProbe")
    if ($byValResult -ne 0) { throw "Unexpected ByVal probe result: $byValResult" }
    if ($byValResult -eq 23) { throw "ByVal probe unexpectedly propagated the output array" }
    Write-Host "PASS generated ByVal Variant output does not propagate (JS expected 23, VBA returned 0)"
    Write-Host "NO-GO for planning engine: unchanged typescript-to-vba 1.0.1 cannot return scheduler results"
} finally {
    if ($harnessCodeModule -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($harnessCodeModule) | Out-Null; $harnessCodeModule = $null }
    if ($harnessComponent -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($harnessComponent) | Out-Null; $harnessComponent = $null }
    if ($byValCodeModule -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($byValCodeModule) | Out-Null; $byValCodeModule = $null }
    if ($byValComponent -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($byValComponent) | Out-Null; $byValComponent = $null }
    if ($safeCodeModule -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($safeCodeModule) | Out-Null; $safeCodeModule = $null }
    if ($safeComponent -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($safeComponent) | Out-Null; $safeComponent = $null }
    if ($vbComponents -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($vbComponents) | Out-Null; $vbComponents = $null }
    if ($vbProject -ne $null) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($vbProject) | Out-Null; $vbProject = $null }
    if ($workbook -ne $null) { $workbook.Close($false); [System.Runtime.InteropServices.Marshal]::ReleaseComObject($workbook) | Out-Null; $workbook = $null }
    if ($excel -ne $null) { $excel.Quit(); [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null; $excel = $null }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()

    for ($attempt = 0; $attempt -lt 50; $attempt++) {
        $automationProcesses = @(Get-Process EXCEL -ErrorAction SilentlyContinue | Where-Object { $existingExcelProcessIds -notcontains $_.Id })
        if ($automationProcesses.Count -eq 0) { break }
        Start-Sleep -Milliseconds 100
    }
    $automationProcesses = @(Get-Process EXCEL -ErrorAction SilentlyContinue | Where-Object { $existingExcelProcessIds -notcontains $_.Id })
    foreach ($process in $automationProcesses) {
        if ($process.MainWindowHandle -eq 0) { Stop-Process -Id $process.Id -Force }
    }

    if (Test-Path -LiteralPath $temporaryDirectory) {
        $resolvedTempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath()).TrimEnd('\') + '\'
        $resolvedTarget = [System.IO.Path]::GetFullPath($temporaryDirectory)
        if (!$resolvedTarget.StartsWith($resolvedTempRoot, [System.StringComparison]::OrdinalIgnoreCase) -or !(Split-Path -Leaf $resolvedTarget).StartsWith("tstvba-poc-excel-")) {
            throw "Refusing to remove unexpected PoC directory: $resolvedTarget"
        }
        Remove-Item -LiteralPath $resolvedTarget -Recurse -Force
    }
}
